apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbiter-bridge-front-prod-deployment
  namespace: orbiter-bridge-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orbiter-bridge-front
      version: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: orbiter-bridge-front
        version: prod
    spec:
      containers:
        - name: orbiter-bridge-front
          image: 952178321851.dkr.ecr.ap-northeast-1.amazonaws.com/orbiter-bridge-frontend:1.0.0
          imagePullPolicy: Always
          command: ['npm']
          args: ['start']
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 3000